// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tpAgencia_Gpo_2;

#nullable disable

namespace tpAgencia_Gpo_2.Migrations
{
    [DbContext(typeof(MiContexto))]
    partial class MiContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tpAgencia_Gpo_2.Ciudad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idVuelo")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<double>("costo")
                        .HasColumnType("float");

                    b.Property<int>("disponibilidad")
                        .HasColumnType("int");

                    b.Property<int>("idCiudad")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idCiudad");

                    b.ToTable("Hotel", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.HotelUsuario", b =>
                {
                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("idHotel", "idUsuario");

                    b.HasIndex("idUsuario");

                    b.ToTable("HotelUsuario");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.ReservaHotel", b =>
                {
                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaDesde")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fechaHasta")
                        .HasColumnType("datetime");

                    b.Property<int>("idReservaHotel")
                        .HasColumnType("int");

                    b.Property<double>("pagado")
                        .HasColumnType("float");

                    b.HasKey("idHotel", "idUsuario");

                    b.HasIndex("idUsuario");

                    b.ToTable("ReservaHotel", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.ReservaVuelo", b =>
                {
                    b.Property<int>("idVuelo")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idReservaVuelo")
                        .HasColumnType("int");

                    b.Property<double>("pagado")
                        .HasColumnType("float");

                    b.HasKey("idVuelo", "idUsuario");

                    b.HasIndex("idUsuario");

                    b.ToTable("ReservaVuelo", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<double>("credito")
                        .HasColumnType("float");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("esAdmin")
                        .HasColumnType("bit");

                    b.Property<int>("intentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Vuelo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CiudadDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadOrigenId")
                        .HasColumnType("int");

                    b.Property<int?>("Ciudadid")
                        .HasColumnType("int");

                    b.Property<string>("aerolinea")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("avion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<double>("costo")
                        .HasColumnType("float");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("vendido")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CiudadDestinoId");

                    b.HasIndex("CiudadOrigenId");

                    b.HasIndex("Ciudadid");

                    b.ToTable("Vuelo", (string)null);
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.VueloUsuario", b =>
                {
                    b.Property<int>("idVuelo")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("idVuelo", "idUsuario");

                    b.HasIndex("idUsuario");

                    b.ToTable("VueloUsuario");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Hotel", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Ciudad", "ubicacion")
                        .WithMany("listHoteles")
                        .HasForeignKey("idCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ubicacion");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.HotelUsuario", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Hotel", "hotel")
                        .WithMany("hotelUsuario")
                        .HasForeignKey("idHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Usuario", "user")
                        .WithMany("hotelUsuario")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hotel");

                    b.Navigation("user");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.ReservaHotel", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Hotel", "miHotel")
                        .WithMany("listMisReservas")
                        .HasForeignKey("idHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Usuario", "miUsuario")
                        .WithMany("listMisReservasHoteles")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("miHotel");

                    b.Navigation("miUsuario");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.ReservaVuelo", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Usuario", "miUsuario")
                        .WithMany("listMisReservasVuelo")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Vuelo", "miVuelo")
                        .WithMany("listMisReservas")
                        .HasForeignKey("idVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("miUsuario");

                    b.Navigation("miVuelo");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Vuelo", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Ciudad", "destino")
                        .WithMany()
                        .HasForeignKey("CiudadDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Ciudad", "origen")
                        .WithMany()
                        .HasForeignKey("CiudadOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Ciudad", null)
                        .WithMany("listVuelos")
                        .HasForeignKey("Ciudadid");

                    b.Navigation("destino");

                    b.Navigation("origen");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.VueloUsuario", b =>
                {
                    b.HasOne("tpAgencia_Gpo_2.Usuario", "user")
                        .WithMany("vueloUsuarios")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tpAgencia_Gpo_2.Vuelo", "vuelo")
                        .WithMany("vueloUsuarios")
                        .HasForeignKey("idVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");

                    b.Navigation("vuelo");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Ciudad", b =>
                {
                    b.Navigation("listHoteles");

                    b.Navigation("listVuelos");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Hotel", b =>
                {
                    b.Navigation("hotelUsuario");

                    b.Navigation("listMisReservas");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Usuario", b =>
                {
                    b.Navigation("hotelUsuario");

                    b.Navigation("listMisReservasHoteles");

                    b.Navigation("listMisReservasVuelo");

                    b.Navigation("vueloUsuarios");
                });

            modelBuilder.Entity("tpAgencia_Gpo_2.Vuelo", b =>
                {
                    b.Navigation("listMisReservas");

                    b.Navigation("vueloUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
